package com.innroad.inncenter.model;

public class CancellationPaymentPopup {

	private String CANCEL_PAYMENT_POLICY_NAME;
	private String CANCEL_PAYMENT_POLICY_DESC;
	private String CANCEL_PAYPMENT_BALANCE;
	private String CANCEL_PAYMENT_AMOUNT;
	private String CANCEL_PAYMENT_TYPE;

	public CancellationPaymentPopup(String cHECK_IN_PAYPMENT_BALANCE, String cHECK_IN_PAYMENT_AMOUNT,
			String cHECK_IN_PAYMENT_TYPE) {
		super();

		CANCEL_PAYPMENT_BALANCE = cHECK_IN_PAYPMENT_BALANCE;
		CANCEL_PAYMENT_AMOUNT = cHECK_IN_PAYMENT_AMOUNT;
		CANCEL_PAYMENT_TYPE = cHECK_IN_PAYMENT_TYPE;
	}

	public CancellationPaymentPopup() {
		super();
		// TODO Auto-generated constructor stub
	}

	public CancellationPaymentPopup(String cANCEL_PAYMENT_POLICY_NAME, String cANCEL_PAYMENT_POLICY_DESC,
			String cANCEL_PAYPMENT_BALANCE, String cANCEL_PAYMENT_AMOUNT, String cANCEL_PAYMENT_TYPE) {
		super();
		CANCEL_PAYMENT_POLICY_NAME = cANCEL_PAYMENT_POLICY_NAME;
		CANCEL_PAYMENT_POLICY_DESC = cANCEL_PAYMENT_POLICY_DESC;
		CANCEL_PAYPMENT_BALANCE = cANCEL_PAYPMENT_BALANCE;
		CANCEL_PAYMENT_AMOUNT = cANCEL_PAYMENT_AMOUNT;
		CANCEL_PAYMENT_TYPE = cANCEL_PAYMENT_TYPE;
	}

	public String getCANCEL_PAYMENT_POLICY_NAME() {
		return CANCEL_PAYMENT_POLICY_NAME;
	}

	public void setCANCEL_PAYMENT_POLICY_NAME(String cANCEL_PAYMENT_POLICY_NAME) {
		CANCEL_PAYMENT_POLICY_NAME = cANCEL_PAYMENT_POLICY_NAME;
	}

	public String getCANCEL_PAYMENT_POLICY_DESC() {
		return CANCEL_PAYMENT_POLICY_DESC;
	}

	public void setCANCEL_PAYMENT_POLICY_DESC(String cANCEL_PAYMENT_POLICY_DESC) {
		CANCEL_PAYMENT_POLICY_DESC = cANCEL_PAYMENT_POLICY_DESC;
	}

	public String getCANCEL_PAYPMENT_BALANCE() {
		return CANCEL_PAYPMENT_BALANCE;
	}

	public void setCANCEL_PAYPMENT_BALANCE(String cANCEL_PAYPMENT_BALANCE) {
		CANCEL_PAYPMENT_BALANCE = cANCEL_PAYPMENT_BALANCE;
	}

	public String getCANCEL_PAYMENT_AMOUNT() {
		return CANCEL_PAYMENT_AMOUNT;
	}

	public void setCANCEL_PAYMENT_AMOUNT(String cANCEL_PAYMENT_AMOUNT) {
		CANCEL_PAYMENT_AMOUNT = cANCEL_PAYMENT_AMOUNT;
	}

	public String getCANCEL_PAYMENT_TYPE() {
		return CANCEL_PAYMENT_TYPE;
	}

	public void setCANCEL_PAYMENT_TYPE(String cANCEL_PAYMENT_TYPE) {
		CANCEL_PAYMENT_TYPE = cANCEL_PAYMENT_TYPE;
	}

	@Override
	public String toString() {

		return "Cancellation Payment Popup : \n"

				+ "\n Payment Balance : " + CANCEL_PAYPMENT_BALANCE + "\n Payment Amount : " + CANCEL_PAYMENT_AMOUNT
				+ "\n Payment Type : " + CANCEL_PAYMENT_TYPE;
	}

}
