package com.innroad.inncenter.model;

public class CheckInPaymentPopup {

	private String CHECK_IN_PAYMENT_POLICY_NAME;
	private String CHECK_IN_PAYMENT_POLICY_DESC;
	private String CHECK_IN_PAYPMENT_BALANCE;
	private String CHECK_IN_PAYMENT_AMOUNT;
	private String CHECK_IN_PAYMENT_TYPE;
	public CheckInPaymentPopup(String cHECK_IN_PAYMENT_POLICY_NAME,String cHECK_IN_PAYMENT_POLICY_DESC, String cHECK_IN_PAYPMENT_BALANCE,
			String cHECK_IN_PAYMENT_AMOUNT, String cHECK_IN_PAYMENT_TYPE) {
		super();
		CHECK_IN_PAYMENT_POLICY_NAME = cHECK_IN_PAYMENT_POLICY_NAME;
		CHECK_IN_PAYMENT_POLICY_DESC = cHECK_IN_PAYMENT_POLICY_DESC;
		CHECK_IN_PAYPMENT_BALANCE = cHECK_IN_PAYPMENT_BALANCE;
		CHECK_IN_PAYMENT_AMOUNT = cHECK_IN_PAYMENT_AMOUNT;
		CHECK_IN_PAYMENT_TYPE = cHECK_IN_PAYMENT_TYPE;
	}
	public CheckInPaymentPopup() {
		super();
		// TODO Auto-generated constructor stub
	}
	public String getCHECK_IN_PAYMENT_POLICY_NAME() {
		return CHECK_IN_PAYMENT_POLICY_NAME;
	}
	public void setCHECK_IN_PAYMENT_POLICY_NAME(String cHECK_IN_PAYMENT_POLICY_NAME) {
		CHECK_IN_PAYMENT_POLICY_NAME = cHECK_IN_PAYMENT_POLICY_NAME;
	}
	public String getCHECK_IN_PAYMENT_POLICY_DESC() {
		return CHECK_IN_PAYMENT_POLICY_DESC;
	}
	public void setCHECK_IN_PAYMENT_POLICY_DESC(String cHECK_IN_PAYMENT_POLICY_DESC) {
		CHECK_IN_PAYMENT_POLICY_DESC = cHECK_IN_PAYMENT_POLICY_DESC;
	}
	public String getCHECK_IN_PAYPMENT_BALANCE() {
		return CHECK_IN_PAYPMENT_BALANCE;
	}
	public void setCHECK_IN_PAYPMENT_BALANCE(String cHECK_IN_PAYPMENT_BALANCE) {
		CHECK_IN_PAYPMENT_BALANCE = cHECK_IN_PAYPMENT_BALANCE;
	}
	public String getCHECK_IN_PAYMENT_AMOUNT() {
		return CHECK_IN_PAYMENT_AMOUNT;
	}
	public void setCHECK_IN_PAYMENT_AMOUNT(String cHECK_IN_PAYMENT_AMOUNT) {
		CHECK_IN_PAYMENT_AMOUNT = cHECK_IN_PAYMENT_AMOUNT;
	}
	public String getCHECK_IN_PAYMENT_TYPE() {
		return CHECK_IN_PAYMENT_TYPE;
	}
	public void setCHECK_IN_PAYMENT_TYPE(String cHECK_IN_PAYMENT_TYPE) {
		CHECK_IN_PAYMENT_TYPE = cHECK_IN_PAYMENT_TYPE;
	}
	@Override
	public String toString() {
		
		return "Check In Payment Popup : \n"
				+ "Policy Name : " + CHECK_IN_PAYMENT_POLICY_NAME
				+ "\n Payment Balance : " + CHECK_IN_PAYPMENT_BALANCE
				+ "\n Payment Amount : " + CHECK_IN_PAYMENT_AMOUNT
				+ "\n Payment Type : " + CHECK_IN_PAYMENT_TYPE;
	}
	
	
}
